add_requires("glm", "stb", "unordered_dense", "nlohmann_json", "zstd")
set_languages("c++20")

target("imgui")
set_kind("static")
add_files("lib/imgui/*.cpp")
add_includedirs("include/imgui")
add_packages("glm")

target("stb")
set_kind("static")
add_files("lib/stb/*.cpp")
add_packages("stb")

target("fractal")
set_kind("binary")
add_files("src/*.cpp")
add_files("src/*.c")
add_includedirs("include", "shaders")
add_packages("glm", "stb", "unordered_dense", "nlohmann_json")
add_cflags("-g", "-O1", "-Wall", "-flto")
add_linkdirs("lib")
add_syslinks("glfw", "GLU", "GL", "dl", "pthread", "zstd")
add_rpathdirs("~/.local/lib")
add_links("FastNoise")
add_deps("imgui", "stb")
